#import "./fragments/category.gql"

query categoryPosts($id: ID = "uncategorized", $first: Int = 10) {
  category(id: $id, idType: SLUG) {
    ...categoryAttributes
    children(first: 10) {
      nodes {
        name
        slug
        id
      }
    }
    posts(first: $first) {
      edges {
        node {
          id
          databaseId
          title
          date
          content(format: RENDERED)
          featuredImage {
            node {
              sourceUrl
              id
            }
          }
        }
      }
    }
    categoryAttrs {
      categoryAttrs {
        id
        altText
        sourceUrl
      }
    }
    description
  }
}
