query categoryEvents($slug: ID = "uncategorized", $first: Int = 10) {
  category(id: $slug, idType: SLUG) {
    id
    count
    name
    slug
    description
    events(first: $first) {
      nodes {
        id
        databaseId
        title(format: RENDERED)
        commentCount
        date
        content
        eventProps {
          duration
          venue
          price
        }

        featuredImage {
          node {
            id
            altText
            sourceUrl
          }
        }
      }
    }
  }
}
