query categoryVideos($id: ID = "uncategorized", $first: Int = 10) {
  category(id: $id, idType: SLUG) {
    id
    databaseId
    count
    name
    slug
    children(first: 10) {
      nodes {
        name
        slug
      }
    }
    description
    videos(first: $first) {
      nodes {
        id
        databaseId
        title
        date
        speakers {
          speakers
        }
        featuredImage {
          node {
            id
            sourceUrl
          }
        }
      }
    }
  }
}
