query events($first: Int = 10) {
  events(first: $first, where: {orderby: {field: DATE, order: ASC}}) {
    nodes {
      id
      databaseId
      title(format: RENDERED)
      commentCount
      date
      eventProps {
        duration
        venue
      }
      categories {
        edges {
          node {
            id
            name
          }
        }
      }
      featuredImage {
        node {
          altText
          sourceUrl
        }
      }
    }
  }
}