query eventParticipants($id: ID!) {
  event(id: $id, idType: DATABASE_ID) {
    comments {
      nodes {
        author {
          node {
            email
            id
            name
            avatar {
              url
            }
          }
        }
      }
    }
  }
}
