query events($first: Int = 10) {
  events(first: $first, where: { orderby: { field: DATE, order: DESC } }) {
    nodes {
      id
      databaseId
      title(format: RENDERED)
      commentCount
      date
      content
      eventProps {
        duration
        venue
        price
      }
      categories {
        edges {
          node {
            id
            name
          }
        }
      }
      featuredImage {
        node {
          id
          altText
          sourceUrl
        }
      }
    }
  }
}
