query eventParticipants($id: ID! ) {
  event(id: $id) {
    comments {
      nodes {
        author {
          node {
            email
            id
            name
            avatar {
              url
            }
          }
        }
      }
    }
  }
}