query fetchMe {
  viewer {
    avatar {
      url
    }
    email
    description
    firstName
    id
    lastName
    nicename
    databaseId
    username
    url
    user_acf {
      occupation
      mobile
      jobLocation
      gen
      phone
    }
  }
}
