query home(
  $first: Int = 10
  $order: OrderEnum = ASC
  $field: PostObjectsConnectionOrderbyEnum = DATE
  $first1: Int = 10
) {
  videos(first: $first, where: { orderby: { field: $field, order: $order } }) {
    nodes {
      id
      title(format: RENDERED)
      content
      speakers {
        speakers
      }
      categories {
        nodes {
          name
          id
        }
      }
      featuredImage {
        node {
          sourceUrl(size: LARGE)
        }
      }
    }
  }
  events(first: $first1) {
    nodes {
      id
      databaseId
      title(format: RENDERED)
      commentCount
      date
      content(format: RENDERED)
      eventProps {
        duration
        venue
      }
      categories {
        edges {
          node {
            id
            name
          }
        }
      }
      featuredImage {
        node {
          id
          altText
          sourceUrl
        }
      }
    }
  }
  category(id: "announcement", idType: SLUG) {
    contentNodes(first: 4) {
      edges {
        node {
          date
          contentTypeName
          ... on Post {
            id
            title(format: RENDERED)
            featuredImage {
              node {
                mediaItemUrl
                id
              }
            }
            categories {
              nodes {
                id
                name
                slug
              }
            }
          }
          id
        }
      }
    }
  }
}
