query Post($idType: PostIdType = DATABASE_ID, $id: ID = "1", $first: Int = 10) {
  post(id: $id, idType: $idType) {
    id
    slug
    title
    featuredImage {
      node {
        altText
        id
        sourceUrl
      }
    }
    date
    content(format: RENDERED)
    categories(first: $first) {
      nodes {
        name
        link
        slug
      }
    }
  }
}
