query videos($first: Int = 8, $parent: Int = 5) {
  categories(where: { parent: $parent }) {
    edges {
      node {
        id
        name
        slug
        videos(first: $first) {
          nodes {
            content(format: RENDERED)
            id
            databaseId
            date
            title
            speakers {
              speakers
            }
            featuredImage {
              node {
                id
                sourceUrl
              }
            }
          }
        }
      }
    }
  }
}
