query video($id: ID!, $first: Int = 3) {
  video(id: $id) {
    id
    content
    title(format: RENDERED)
    date
    speakers {
      speakers
    }
    categories(first: $first) {
      nodes {
        name
        slug
        databaseId
        id
      }
    }
  }
}
