query video($id: ID!, $first: Int = 3, $idType: VideoIdType = ID) {
  video(id: $id, idType: $idType) {
    id
    content
    title(format: RENDERED)
    date
    speakers {
      speakers
    }
    featuredImage {
      node {
        sourceUrl
      }
    }
    categories(first: $first) {
      nodes {
        name
        slug
        databaseId
        id
      }
    }
  }
}
